apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: sownia
type: Opaque
stringData:
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
  LANGCHAIN_API_KEY: {{ .Values.secrets.langchainApiKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
